// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVFGCVIlE_5KnxSnELd2eQz992XurW9Qw',
    appId: '1:1072948429046:web:d471c3c41b752859972cd7',
    messagingSenderId: '1072948429046',
    projectId: 'flutter-app-9b780',
    authDomain: 'flutter-app-9b780.firebaseapp.com',
    storageBucket: 'flutter-app-9b780.firebasestorage.app',
    measurementId: 'G-S3M36DNPMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1kL1EQFmSJCW-j06CrMTBfUX7qnk2P_o',
    appId: '1:1072948429046:android:a91f8e1a2a1c2ad0972cd7',
    messagingSenderId: '1072948429046',
    projectId: 'flutter-app-9b780',
    storageBucket: 'flutter-app-9b780.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rMwxCUZrCIBGbvYvVFXdH6T3ZBupojw',
    appId: '1:1072948429046:ios:5026e45408b20d02972cd7',
    messagingSenderId: '1072948429046',
    projectId: 'flutter-app-9b780',
    storageBucket: 'flutter-app-9b780.firebasestorage.app',
    iosClientId: '1072948429046-99qh4p4q1kkrbti2o2h6fpbm7vok1621.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0rMwxCUZrCIBGbvYvVFXdH6T3ZBupojw',
    appId: '1:1072948429046:ios:5026e45408b20d02972cd7',
    messagingSenderId: '1072948429046',
    projectId: 'flutter-app-9b780',
    storageBucket: 'flutter-app-9b780.firebasestorage.app',
    iosClientId: '1072948429046-99qh4p4q1kkrbti2o2h6fpbm7vok1621.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVFGCVIlE_5KnxSnELd2eQz992XurW9Qw',
    appId: '1:1072948429046:web:09fd1e147b8215ca972cd7',
    messagingSenderId: '1072948429046',
    projectId: 'flutter-app-9b780',
    authDomain: 'flutter-app-9b780.firebaseapp.com',
    storageBucket: 'flutter-app-9b780.firebasestorage.app',
    measurementId: 'G-VXG68R874K',
  );
}
